---
# 仅在初始化节点上获取admin.conf
- name: Fetch admin.conf from init node
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: /tmp/k8s_admin.conf
    flat: yes
  when: (is_init is defined) and (is_init == 1)

# 向所有非初始化节点分发admin.conf
- name: Distribute admin.conf to all nodes
  copy:
    src: /tmp/k8s_admin.conf
    dest: /etc/kubernetes/admin.conf
    mode: 0644
  when: (is_init is undefined) or (is_init != 1)

# 为所有节点配置kubectl
- name: Configure kubectl for all nodes
  shell: |
    mkdir -p $HOME/.kube && \
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && \
    sudo chown $(id -u):$(id -g) $HOME/.kube/config && \
    kubectl completion bash > /etc/bash_completion.d/kubectl
  when: (is_init is undefined) or (is_init != 1)
