---
- include_tasks: 01_install_pkgs.yml
- include_tasks: 02_init_cluster.yml
- include_tasks: 03_add_master.yml
- include_tasks: 04_add_worker.yml
- include_tasks: 05_install_helm.yml
- include_tasks: 06_distribute_kubeconfig.yml
- include_tasks: 07_install_cni_kubeovn.yml