---
- name: 创建临时目录存放依赖包
  file:
    path: "/home/packages"
    state: directory
    mode: '0755'

- name: 查找所有依赖包（deb）文件
  ansible.builtin.find:
    path: "{{ playbook_dir }}/packages/"
    patterns: '*.deb'
    recurse: no
  delegate_to: localhost
  register: deb_files
  run_once: true  # 仅在控制节点执行一次


- name: 复制依赖包到目标节点
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/packages/{{ item | basename }}"
    dest: "/home/packages/{{ item | basename }}"
    mode: '0644'
  with_items: "{{ deb_files.files | map(attribute='path') | list }}"
  when: deb_files.files | length > 0  # 确保只在有文件时执行

- name: 停止 systemd-timesyncd 服务
  systemd:
    name: systemd-timesyncd.service
    state: stopped
    enabled: no
  ignore_errors: true

- name: 卸载 systemd-timesyncd 包
  apt:
    name: systemd-timesyncd
    state: absent
    autoremove: yes  # 自动移除依赖的无用包
    purge: yes
  ignore_errors: true

- name: 安装依赖包
  shell: "sudo dpkg -i /home/packages/*.deb"
  when: deb_files.files | length > 0  # 确保只在有文件时执行


