---
- name: Remove ntp package
  apt:
    name: 
      - ntp
    state: absent

# 使用chrony 代替 systemd-timesyncd


- name: Install chrony package
  apt:
    name: chrony
    state: present

- name: Configure chronyd service
  template:
    src: chrony.j2
    dest: /etc/chrony.conf

- name: Restart chronyd.service
  systemd:
    name: chronyd.service
    state: restarted
    enabled: yes

