---
# 清理 Containerd 残留（如果存在）
- name: Stop and disable containerd
  systemd:
    name: containerd
    state: stopped
    enabled: no
  ignore_errors: true

- name: Remove containerd config and binaries
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/containerd
    - /usr/local/bin/containerd
  ignore_errors: true

